# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='liked_post',
        ),
        migrations.RemoveField(
            model_name='member',
            name='scraped_post',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_member',
            field=models.ManyToManyField(related_name='liked_post', to='posting.Member'),
        ),
        migrations.AddField(
            model_name='post',
            name='scraped_member',
            field=models.ManyToManyField(related_name='scraped_post', to='posting.Member'),
        ),
    ]
