# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:46
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20160125_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=audiofield.fields.AudioField(upload_to='uploads/tracks/converted/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='download',
            field=models.FileField(help_text='A track should be .mp3, .wav, .ogg smaller than 10MiB', upload_to='uploads/tracks/raw/%Y/%m/%d/'),
        ),
    ]
