# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20160130_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='download',
        ),
    ]
