# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_remove_track_playtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.Creator'),
        ),
    ]
