# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_auto_20160131_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(help_text='A track should be smaller than 10MiB', upload_to='uploads/tracks/converted/%Y/%m/%d/'),
        ),
    ]
