# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_auto_20160203_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.Post')),
            ],
        ),
    ]
