# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0013_auto_20160213_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='picture',
            field=models.ImageField(default='default/user_default.png', upload_to='uploads/userimage'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='salutation',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='journal',
            name='bgimage',
            field=models.ImageField(blank=True, default='default/background_default.png', upload_to='uploads/bgimage/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(help_text='\ud2b8\ub799\uc740 10MiB \ubbf8\ub9cc\uc73c\ub85c \uc62c\ub824\uc8fc\uc138\uc694.', upload_to='uploads/tracks/converted/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.CharField(help_text='\ud2b8\ub799\uc5d0 \ub300\ud55c \uac04\ub2e8\ud55c \uc124\uba85\uc744 \uc368\uc8fc\uc138\uc694.', max_length=140),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(blank=True, default='default/background_default.png', help_text='\ubc30\uacbd\uc73c\ub85c \uc4f0\uc77c \uc774\ubbf8\uc9c0\uc785\ub2c8\ub2e4. 2MiB \ubbf8\ub9cc\uc758 \uc774\ubbf8\uc9c0\ub9cc \uc62c\ub824\uc8fc\uc138\uc694.', upload_to='uploads/images/%Y/%m/%d'),
        ),
    ]
