# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0014_auto_20160221_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='bgimage',
            field=models.ImageField(default='default/background_default.png', upload_to='uploads/bgimage/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='default/background_default.png', help_text='\ubc30\uacbd\uc73c\ub85c \uc4f0\uc77c \uc774\ubbf8\uc9c0\uc785\ub2c8\ub2e4. 2MiB \ubbf8\ub9cc\uc758 \uc774\ubbf8\uc9c0\ub9cc \uc62c\ub824\uc8fc\uc138\uc694.', upload_to='uploads/images/%Y/%m/%d'),
        ),
    ]
