# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0015_auto_20160221_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='salutation',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
