# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0018_auto_20160222_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='picture',
            field=models.ImageField(default='/media/defaults/user_default.png', upload_to='uploads/userimage'),
        ),
    ]
