# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='uploads/image/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='JournalUpload',
        ),
    ]
